version: "3.3"
services:

  mariadb:
      image: bitnami/mariadb:latest
      container_name: mariadb
      ports:
        - 3306:3306
      environment:
        - "MARIADB_ROOT_PASSWORD=mypassword"
        - "MARIADB_USER=neuser"
        - "MARIADB_PASSWORD=mypass"
        - "MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=155"
      network_mode: host
      restart: on-failure
      volumes:
      - ${PWD}/mariadb:/var/lib/mysql

  db_admin:
    depends_on:
      - mariadb
    container_name: db_admin_aku
    image: phpmyadmin/phpmyadmin
    environment:
      - "PMA_HOST=mariadb"
      - "MYSQL_ROOT_PASSWORD=mypassword"
    ports:
      - "8084:80"
